### ISSUE TITLE
undefined local variable or method `logger' 

### ISSUE THREAD

**Issue by Nkadze** [mikeyhew/shopify_api_mixins#2]
Hi,
I'm getting this error 
`undefined local variable or method logger for #<ShopifyAPI::Connection:0x007fb485133580>`
on **retry_on429.rb** line 24
` logger&.warn "Got a 429, will retry in #{wait_time} seconds"`

Maybe it has something to do with [this commit](https://github.com/mikeyhew/shopify_api_mixins/commit/48421cf1a7fb09b2a250686f54d2e53c7347a751)?

**Comment by mikeyhew** [comment]
@Nkadze the `logger` method was added in https://github.com/rails/activeresource/pull/259. Can you update `activeresource` to the latest commit in the master branch, and let me know if that fixes it?

**Comment by Nkadze** [comment]
Thanks @mikeyhew , it worked
