### ISSUE TITLE
Invalid gemspec

### ISSUE THREAD

**Issue by Nkadze** [mikeyhew/shopify_api_mixins#6]
Hi all, I have strange error when bundling:

```bash
You have one or more invalid gemspecs that need to be fixed.
The gemspec at
/home/username/.bundle/ruby/2.3.0/shopify_api_mixins-179c23164e99/shopify_api_mixins.gemspec
is not valid. Please fix this gemspec.
The validation error was '"TODO: Put your gem's website or public repo
URL here." is not a URI'
```

gemfile looks like: 
```ruby
gem 'shopify_api_mixins', git: 'https://github.com/mikeyhew/shopify_api_mixins.git'
```
If I comment git source for gem bundler throws:

```bash
Could not find gem 'shopify_api_mixins' in any of the gem sources
listed in your Gemfile.
```

It was working few months ago when I started using this gem, but now it's not bundling 

thanks in advance

**Comment by mikeyhew** [comment]
Hey @Nkadze, thanks for reporting the issue.

What version of bundler are you using? My guess is they started validating the gem's repository or website field.

Can you edit that field in the gemspec file so it points to this repository, test it with your app to make sure it works, and then open a PR with your changes?

**Comment by Nkadze** [comment]
Hi, 
bundler version is 1.16.0, but strangely I couldn't reproduce issue again after 3 hours driving westwards :smile:

**Comment by mikeyhew** [comment]
Haha, let's hope it's not a bug that depends on which timezone you're in

**Comment by Nkadze** [comment]
Ok, I think issue can be closed

**Comment by mikeyhew** [comment]
Sure thing :thumbsup:
